name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  ARCHITECTURE: linux-amd64
  IMAGE_NAME: dreytac/plex-media-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Prepare
        id: prep
        run: |
          echo ::set-output name=tag::${{ env.IMAGE_NAME }}:${GITHUB_REF//refs\/heads\//}-${GITHUB_SHA:0:7}-${{ env.ARCHITECTURE }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.prep.outputs.tag }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest
          build-args: |
            GITHUB_TOKEN=${{ secrets.PERSONAL_TOKEN }}
